# Generated by Django 4.0.6 on 2022-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMayoristas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]
