# Generated by Django 4.0.6 on 2022-09-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_remove_productos_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='registromayoristas',
            options={'verbose_name': 'Mayorista', 'verbose_name_plural': 'Mayoristas'},
        ),
        migrations.AlterModelOptions(
            name='sorteo',
            options={'verbose_name': 'Sorteo', 'verbose_name_plural': 'Sorteos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registromayoristas',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
