# Generated by Django 4.0.6 on 2022-09-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
