# Generated by Django 4.0.6 on 2022-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromayoristas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
