# Generated by Django 4.0.6 on 2022-09-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0006_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
