# Generated by Django 4.0.6 on 2022-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
