# Generated by Django 4.0.6 on 2022-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_avatar_fecha_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar'),
        ),
    ]
